version: '3.9'

services:
  app:
    image: my_auth_api
    container_name: my_auth_api
    build: .
    restart: always
    volumes:
      - ./app:/app
    command: uvicorn main:app --workers 2 --host 0.0.0.0 --port ${APP_PORT}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - APP_PORT
    healthcheck:
      test: python -c "import os, httpx; httpx.get(f'http://127.0.0.1:{os.environ[\"APP_PORT\"]}')" || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
