version: '3.9'

services:
  app:
    image: my_auth_api
    build: .
    restart: always
    volumes:
      - ./app:/app
    command: uvicorn main:app --workers 2 --host 0.0.0.0 --port ${APP_PORT}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    healthcheck:
      test: curl --fail http://127.0.0.1:${APP_PORT} || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
